// Original practice material authored for this project; not copied from official tests.
const question = (id, text, options, answer, evidence, tag = "paraphrase") => ({
  id,
  text,
  options,
  answer,
  evidence,
  tag,
});
const reading = [
  {
    id: "r1",
    skill: "Reading",
    title: "Khi thành phố trở nên xanh hơn",
    subtitle: "The quiet value of urban gardens",
    topic: "Môi trường",
    band: 5,
    minutes: 15,
    type: "True / False / Not Given",
    text: `A. On an unused plot beside a railway station, residents of Bellford created a community garden in 2021. The council provided tools, but local volunteers paid for the seeds. The garden is open to visitors every afternoon.\n\nB. At first, most volunteers hoped to grow cheaper vegetables. After a year, however, many said that meeting neighbours was the most valuable outcome. A survey of 40 participants found that 28 had made at least one new friend through the project. No comparison was made with residents who did not participate.\n\nC. The garden also collects rainwater from a nearby roof. During the summer, this supplies about half the water needed by the plants. The remaining water comes from the town supply. Plans to install a larger tank have been postponed because the council has not yet approved the funding.\n\nD. Although the project occupies only a small area, its organisers believe it offers a useful model for other neighbourhoods. They caution that success depends on regular volunteers rather than simply having available land.`,
    questions: [
      question(
        "r1q1",
        "The council paid for the seeds.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "FALSE",
        "The council provided tools, but local volunteers paid for the seeds.",
        "NOT_GIVEN_as_FALSE",
      ),
      question(
        "r1q2",
        "Most survey participants made a new friend.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "TRUE",
        "A survey of 40 participants found that 28 had made at least one new friend.",
      ),
      question(
        "r1q3",
        "Non-participants felt less connected to their neighbours.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "NOT GIVEN",
        "No comparison was made with residents who did not participate.",
        "NOT_GIVEN_as_FALSE",
      ),
      question(
        "r1q4",
        "Rainwater provides all the water required in summer.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "FALSE",
        "During the summer, this supplies about half the water needed by the plants.",
      ),
      question(
        "r1q5",
        "A larger tank has already been installed.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "FALSE",
        "Plans to install a larger tank have been postponed.",
      ),
      question(
        "r1q6",
        "The organisers consider consistent participation essential.",
        ["TRUE", "FALSE", "NOT GIVEN"],
        "TRUE",
        "Success depends on regular volunteers rather than simply having available land.",
      ),
    ],
  },
  {
    id: "r2",
    skill: "Reading",
    title: "Một tuần làm việc linh hoạt",
    subtitle: "Rethinking the working week",
    topic: "Công việc",
    band: 6,
    minutes: 15,
    type: "Multiple choice",
    text: `A. A small software company, Northline, tested a four-day working week for six months. Employees received their usual salary and worked 32 hours rather than 40. To avoid losing time, the team shortened meetings and created two daily periods during which internal messages could wait.\n\nB. Customer support remained available five days a week because employees took different days off. Some customers initially worried that responses would be slower. Records from the trial showed, however, that the average response time was almost unchanged. The number of customer complaints was not recorded.\n\nC. Staff reported feeling more rested, but a few found the shorter week stressful when deadlines coincided. The company therefore kept the arrangement while allowing teams to return temporarily to five days during unusually busy periods. The director said the result should not be interpreted as proof that every industry could adopt the same policy.`,
    questions: [
      question(
        "r2q1",
        "How did Northline reduce distractions?",
        [
          "By banning all messages",
          "By introducing protected work periods",
          "By employing fewer people",
        ],
        "By introducing protected work periods",
        "The team ... created two daily periods during which internal messages could wait.",
      ),
      question(
        "r2q2",
        "What happened to customer response times?",
        [
          "They stayed broadly similar",
          "They doubled",
          "They were not measured",
        ],
        "They stayed broadly similar",
        "The average response time was almost unchanged.",
      ),
      question(
        "r2q3",
        "Why could customers still get help on Fridays?",
        [
          "Staff worked longer hours",
          "Employees had different days off",
          "An outside company took over",
        ],
        "Employees had different days off",
        "Employees took different days off.",
      ),
      question(
        "r2q4",
        "What limitation did the director acknowledge?",
        [
          "The trial used no employees",
          "The findings may not apply to all industries",
          "All deadlines were missed",
        ],
        "The findings may not apply to all industries",
        "The result should not be interpreted as proof that every industry could adopt the same policy.",
      ),
    ],
  },
];
const listening = [
  {
    id: "l1",
    skill: "Listening",
    title: "Đăng ký lớp học cuối tuần",
    subtitle: "A conversation at the community centre",
    topic: "Đời sống",
    band: 4.5,
    minutes: 10,
    type: "Multiple choice",
    text: `Receptionist: Good morning, Riverton Community Centre. How can I help?\nVisitor: I'd like to join the weekend photography course. I saw it starts at nine.\nReceptionist: That was the old schedule. It now starts at half past nine on Saturday.\nVisitor: Is it still in the main hall?\nReceptionist: No, the hall is being repaired. Please come to Room Twelve, next to the library.\nVisitor: Do I need my own camera?\nReceptionist: We can lend you one, but please bring a notebook. The fee is forty pounds for four sessions.\nVisitor: I thought it was fifty.\nReceptionist: That includes the advanced course. This beginner course is forty. Please register by Thursday afternoon.`,
    questions: [
      question(
        "l1q1",
        "When does the course start?",
        ["9:00", "9:30", "10:30"],
        "9:30",
        "It now starts at half past nine on Saturday.",
        "distractor",
      ),
      question(
        "l1q2",
        "Where will the course take place?",
        ["The main hall", "Room Twelve", "Inside the library"],
        "Room Twelve",
        "Please come to Room Twelve, next to the library.",
        "distractor",
      ),
      question(
        "l1q3",
        "What should the visitor bring?",
        ["A camera", "A notebook", "A laptop"],
        "A notebook",
        "We can lend you one, but please bring a notebook.",
      ),
      question(
        "l1q4",
        "How much is the beginner course?",
        ["£40", "£50", "£14"],
        "£40",
        "This beginner course is forty.",
        "numbers",
      ),
      question(
        "l1q5",
        "What is the registration deadline?",
        ["Saturday morning", "Friday afternoon", "Thursday afternoon"],
        "Thursday afternoon",
        "Please register by Thursday afternoon.",
      ),
    ],
  },
  {
    id: "l2",
    skill: "Listening",
    title: "Một nghiên cứu về giấc ngủ",
    subtitle: "Short academic talk · Part 4 style",
    topic: "Sức khỏe",
    band: 6,
    minutes: 12,
    type: "Multiple choice",
    text: `Today I will describe a pilot study about evening screen use. Thirty volunteers kept a sleep diary for three weeks. In the first week, they followed their normal routines. In the next two weeks, they stopped using phones and tablets one hour before bed. On average, participants reported falling asleep twelve minutes earlier. However, this finding came from their diaries, not from laboratory measurements. We did not control caffeine consumption, and some people changed their exercise routines. Consequently, we cannot conclude that reduced screen use alone caused the improvement. Our next study will include a comparison group and wearable sleep monitors.`,
    questions: [
      question(
        "l2q1",
        "How long did the study last?",
        ["One week", "Two weeks", "Three weeks"],
        "Three weeks",
        "Thirty volunteers kept a sleep diary for three weeks.",
        "numbers",
      ),
      question(
        "l2q2",
        "What did participants do during the first week?",
        [
          "Stopped drinking coffee",
          "Kept their usual routines",
          "Used sleep monitors",
        ],
        "Kept their usual routines",
        "In the first week, they followed their normal routines.",
      ),
      question(
        "l2q3",
        "What was the source of the reported improvement?",
        ["Laboratory tests", "Personal diaries", "Medical records"],
        "Personal diaries",
        "This finding came from their diaries, not from laboratory measurements.",
      ),
      question(
        "l2q4",
        "Why is the conclusion uncertain?",
        [
          "Other habits also changed",
          "No one completed the diary",
          "Screens were never used",
        ],
        "Other habits also changed",
        "We did not control caffeine consumption, and some people changed their exercise routines.",
        "inference",
      ),
    ],
  },
];
const writing = [
  {
    id: "w1",
    skill: "Writing",
    title: "Công nghệ & cách chúng ta học",
    subtitle: "Task 2 · Opinion essay",
    topic: "Giáo dục",
    band: 5.5,
    minutes: 40,
    type: "Task 2",
    minimumWords: 250,
    text: "Some people believe that online learning provides greater opportunities than traditional classroom education. To what extent do you agree or disagree? Give reasons for your answer and include relevant examples from your own knowledge or experience.",
  },
  {
    id: "w2",
    skill: "Writing",
    title: "Di chuyển trong thành phố",
    subtitle: "Academic Task 1 · Data table",
    topic: "Giao thông",
    band: 5,
    minutes: 20,
    type: "Task 1",
    minimumWords: 150,
    text: "The table shows the percentage of commuters using four transport modes in the fictional city of Westbridge in 2015 and 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    table: [
      ["Mode", "2015", "2025"],
      ["Car", "55%", "40%"],
      ["Bus", "25%", "30%"],
      ["Bicycle", "10%", "20%"],
      ["Walking", "10%", "10%"],
    ],
  },
  {
    id: "w3",
    skill: "Writing",
    title: "Viết thư cho thư viện",
    subtitle: "General Training · Task 1",
    topic: "Cộng đồng",
    band: 5,
    minutes: 20,
    type: "Task 1",
    mode: "General Training",
    minimumWords: 150,
    text: "Your local library is considering reducing its evening opening hours. Write a letter to the library manager. Explain how you use the library, describe how the change would affect you, and suggest an alternative solution.",
  },
];
const speaking = [
  {
    id: "s1",
    skill: "Speaking",
    title: "Một nơi bạn muốn quay lại",
    subtitle: "Part 2 · Places & memories",
    topic: "Du lịch",
    band: 5.5,
    minutes: 8,
    type: "Part 2",
    text: "Describe a place you visited that you would like to return to. You should say: where it is; when you went there; what you did there; and explain why you would like to visit it again.",
    followups: [
      "Why do people enjoy returning to familiar places?",
      "How can tourism affect local communities?",
      "Should cities limit the number of visitors to popular sites?",
    ],
  },
  {
    id: "s2",
    skill: "Speaking",
    title: "Thói quen mỗi ngày",
    subtitle: "Part 1 · Daily routines",
    topic: "Đời sống",
    band: 4,
    minutes: 5,
    type: "Part 1",
    text: "What do you usually do in the morning? Has your daily routine changed since you were younger? What part of your day do you enjoy most? Why?",
    followups: [
      "Would you like to change your routine? Why?",
      "What helps you stay organised?",
    ],
  },
  {
    id: "s3",
    skill: "Speaking",
    title: "Công nghệ trong tương lai",
    subtitle: "Part 3 · Abstract discussion",
    topic: "Công nghệ",
    band: 6.5,
    minutes: 8,
    type: "Part 3",
    text: "How has technology changed the way people communicate? Do you think these changes have improved relationships? Who should be responsible for teaching children to use technology safely?",
    followups: [
      "Can digital communication replace meeting face to face?",
      "Should governments regulate emerging technologies?",
    ],
  },
];
export const lessons = [...reading, ...listening, ...writing, ...speaking];
export const vocabulary = [
  [
    "sustainable",
    "bền vững",
    "adjective",
    "able to continue without damaging the environment",
    "sustainable development",
    "Cities need sustainable transport systems.",
    "sustainability",
    "Không nhầm sustainable với sustained.",
  ],
  [
    "commute",
    "đi lại giữa nhà và nơi làm việc",
    "verb",
    "to travel regularly between home and work",
    "commute to work",
    "She commutes by train every morning.",
    "commuter",
    "Dùng commute to, không dùng commute at.",
  ],
  [
    "implement",
    "triển khai",
    "verb",
    "to put a plan into action",
    "implement a policy",
    "The council will implement the new policy next year.",
    "implementation",
    "Implement đi với plan/policy, không phải invent.",
  ],
  [
    "consequence",
    "hệ quả",
    "noun",
    "a result of an action or situation",
    "an unintended consequence",
    "One consequence of remote work is reduced travel.",
    "consequently",
    "Phân biệt cause (nguyên nhân) và consequence (hệ quả).",
  ],
  [
    "significant",
    "đáng kể",
    "adjective",
    "large or important enough to notice",
    "a significant increase",
    "There was a significant increase in bicycle use.",
    "significantly",
    "Dùng significantly trước động từ: increased significantly.",
  ],
  [
    "allocate",
    "phân bổ",
    "verb",
    "to give resources for a particular purpose",
    "allocate resources",
    "Schools should allocate more time to practical skills.",
    "allocation",
    "Allocate something to someone/something.",
  ],
  [
    "whereas",
    "trong khi (đối chiếu)",
    "conjunction",
    "used to contrast two facts",
    "whereas others",
    "Some people prefer cities, whereas others enjoy rural life.",
    "—",
    "Whereas để đối chiếu, không diễn đạt thời gian.",
  ],
  [
    "reliable",
    "đáng tin cậy",
    "adjective",
    "able to be trusted or depended on",
    "reliable evidence",
    "Reliable evidence is essential for a strong argument.",
    "reliability",
    "Reliable mô tả nguồn; reliant nghĩa là phụ thuộc.",
  ],
  [
    "accessible",
    "dễ tiếp cận",
    "adjective",
    "easy to reach or use",
    "accessible education",
    "Online courses can make education more accessible.",
    "accessibility",
    "Accessible to, không dùng accessible for mọi ngữ cảnh.",
  ],
  [
    "outweigh",
    "vượt trội hơn",
    "verb",
    "to be greater in importance than something else",
    "benefits outweigh drawbacks",
    "The benefits may outweigh the drawbacks.",
    "—",
    "Outweigh là ngoại động từ: không cần than.",
  ],
  [
    "retain",
    "giữ lại",
    "verb",
    "to keep or continue to have",
    "retain information",
    "Regular review helps learners retain information.",
    "retention",
    "Retain khác regain (lấy lại).",
  ],
  [
    "perspective",
    "góc nhìn",
    "noun",
    "a particular way of thinking about something",
    "a different perspective",
    "Travel can offer a different perspective on everyday life.",
    "—",
    "From my perspective, không dùng in my perspective.",
  ],
].map((v, i) => ({
  id: `v${i + 1}`,
  lemma: v[0],
  gloss: v[1],
  pos: v[2],
  definition: v[3],
  collocation: v[4],
  example: v[5],
  family: v[6],
  error: v[7],
  level: 5 + (i % 3) * 0.5,
}));

// Small original diagnostic bank. Difficulty is instructional, not psychometrically calibrated.
const contexts = [
  [
    "library",
    "The library opens at eight on weekdays, but on Saturdays it opens two hours later.",
    "When does the library open on Saturday?",
    ["8:00", "10:00", "12:00"],
    "10:00",
    "numbers",
  ],
  [
    "transport",
    "The new bus service runs every twenty minutes. Previously, passengers waited half an hour between buses.",
    "How often did buses run previously?",
    ["Every 20 minutes", "Every 30 minutes", "Every 10 minutes"],
    "Every 30 minutes",
    "distractor",
  ],
  [
    "education",
    "Students can borrow laptops, although they must return them before leaving the building.",
    "What restriction applies to laptops?",
    [
      "They cannot leave the building",
      "Only teachers can use them",
      "They must be purchased",
    ],
    "They cannot leave the building",
    "paraphrase",
  ],
  [
    "health",
    "The clinic recommends walking regularly, but says people should consult a doctor before starting vigorous exercise.",
    "What is recommended before intense exercise?",
    ["Buying new shoes", "Getting medical advice", "Walking for a year"],
    "Getting medical advice",
    "paraphrase",
  ],
  [
    "work",
    "Sales increased after the shop extended its hours. However, a nearby competitor closed at the same time, so the effect of longer opening cannot be isolated.",
    "Why is the cause of increased sales uncertain?",
    [
      "Another change occurred simultaneously",
      "Opening hours stayed the same",
      "Sales were not recorded",
    ],
    "Another change occurred simultaneously",
    "inference",
  ],
  [
    "environment",
    "Only residents who registered before June received a free recycling bin. Visitors could buy one at the office.",
    "Who received a free bin?",
    ["All visitors", "Residents who registered early", "Anyone at the office"],
    "Residents who registered early",
    "detail",
  ],
  [
    "community",
    "The proposed playground was popular among parents, yet construction was delayed because the soil required safety tests.",
    "What delayed construction?",
    [
      "Lack of parental support",
      "A need to examine the ground",
      "A shortage of playground designs",
    ],
    "A need to examine the ground",
    "paraphrase",
  ],
  [
    "research",
    "Participants reported better concentration, but the researchers noted that self-reports might reflect expectations rather than measurable improvement.",
    "What concern did researchers express?",
    [
      "Reports may be influenced by expectations",
      "Participants had no expectations",
      "Concentration cannot ever be measured",
    ],
    "Reports may be influenced by expectations",
    "inference",
  ],
  [
    "travel",
    "The museum ticket includes the permanent collection. The temporary exhibition costs an additional six pounds.",
    "What does the standard ticket cover?",
    [
      "Both exhibitions",
      "The permanent collection only",
      "The temporary exhibition only",
    ],
    "The permanent collection only",
    "detail",
  ],
  [
    "food",
    "The cafe used to import all its fruit. It now buys apples locally, while tropical fruits still come from overseas.",
    "Which fruit is now sourced locally?",
    ["All tropical fruit", "Apples", "No fruit"],
    "Apples",
    "distractor",
  ],
  [
    "technology",
    "Although the app is free to download, users need a monthly subscription to save more than three projects.",
    "When is payment required?",
    [
      "To download the app",
      "To save over three projects",
      "To open any project",
    ],
    "To save over three projects",
    "detail",
  ],
  [
    "arts",
    "The gallery extended its evening hours in response to feedback from workers who could not visit during the day.",
    "Why were the hours extended?",
    [
      "To accommodate working visitors",
      "To reduce lighting costs",
      "To replace daytime visits",
    ],
    "To accommodate working visitors",
    "paraphrase",
  ],
  [
    "housing",
    "Insulation reduced heating costs in most homes, though savings varied according to building age and residents’ habits.",
    "What can be concluded about savings?",
    [
      "They were identical everywhere",
      "They depended on multiple factors",
      "They occurred only in new homes",
    ],
    "They depended on multiple factors",
    "inference",
  ],
  [
    "sports",
    "The pool closes for cleaning at noon on Tuesday. On all other weekdays, it stays open until nine in the evening.",
    "When does the pool close on Tuesday?",
    ["9 pm", "12 noon", "9 am"],
    "12 noon",
    "distractor",
  ],
  [
    "science",
    "The trial showed an association between gardening and wellbeing, but its observational design did not establish causation.",
    "What did the trial establish?",
    [
      "That gardening causes happiness",
      "A relationship, not a proven cause",
      "That wellbeing prevents gardening",
    ],
    "A relationship, not a proven cause",
    "inference",
  ],
  [
    "finance",
    "Customers can cancel within fourteen days for a full refund, provided they have not used the service.",
    "What condition is required for a full refund?",
    [
      "The service has not been used",
      "Cancellation after a month",
      "A second purchase",
    ],
    "The service has not been used",
    "detail",
  ],
  [
    "nature",
    "Bird numbers rose in the protected zone while remaining stable outside it. Migration patterns were not measured.",
    "Which statement is supported?",
    [
      "Bird numbers increased everywhere",
      "Numbers increased within the protected area",
      "Migration caused the increase",
    ],
    "Numbers increased within the protected area",
    "inference",
  ],
  [
    "city",
    "The committee favoured renovating the station over replacing it, citing lower costs and the value of its historic architecture.",
    "Why was renovation preferred?",
    [
      "It was cheaper and preserved heritage",
      "A new station was impossible",
      "The old station had no historic value",
    ],
    "It was cheaper and preserved heritage",
    "paraphrase",
  ],
];
export const diagnosticItems = ["Reading", "Listening"].flatMap((skill, s) =>
  contexts.map((c, i) => ({
    id: `d-${s}-${i}`,
    skill,
    topic: c[0],
    text: skill === "Listening" ? `Here is an announcement. ${c[1]}` : c[1],
    question: c[2],
    options: c[3],
    answer: c[4],
    evidence: c[1],
    tag: c[5],
    difficulty: 3.5 + (i % 8) * 0.5,
  })),
);
export function publicLesson(l) {
  return {
    ...l,
    questions: l.questions?.map(({ answer, evidence, tag, ...q }) => q),
  };
}
export function publicDiagnostic(q) {
  const { answer, evidence, tag, ...rest } = q;
  return rest;
}
